name: test gcp connection

on:
  workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/240848517511/locations/global/workloadIdentityPools/gitact/providers/my-provider
          service_account: git-actions@production-pipeline-488413.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Access secret
        run: |
          gcloud secrets versions access latest --secret="my-secret"