name: build-and-push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: production-pipeline-488413
      REGION: us-central1
      REPO: dbt-registry
      IMAGE: dbt-project

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/240848517511/locations/global/workloadIdentityPools/gitact/providers/my-provider
          service_account: git-actions@production-pipeline-488413.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/dbt-project
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .

      - name: Push
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/dbt-project
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest